### ISSUE TITLE
Tool needs to support input and output files.

### ISSUE THREAD

**Issue by rhatdan** [containers/oci-seccomp-bpf-hook#10]
Perhaps

```
sudo podman run --annotation io.podman.trace-syscall=if:/tmp/seccomp-old.json,of:/tmp/seccomp.json  IMAGE COMMAND
```
Annotation becomes a comma separate list of options to the plugin.

```
sudo podman run --annotation io.podman.trace-syscall=if:/tmp/seccomp.json,of:/tmp/seccomp.json  IMAGE COMMAND
```
Would update the existing seccomp.json file.
```
sudo podman run --annotation io.podman.trace-syscall=of:/tmp/seccomp.json  IMAGE COMMAND
```
Should fail if the /tmp/seccomp.json file exists.

**Comment by vrothberg** [comment]
I like the idea and the syntax.

> Should fail if the /tmp/seccomp.json file exists.

Not sure about that. It seems like a restriction that could break common workflows. For instance, in the bats tests we're first generating a temp file and use that to feed the hook.

**Comment by rhatdan** [comment]
Well if it doesn't fail, then it needs to overwrite.

My concern is with people running the command multiple times with different tests, They may expect it to be cumulative, but currently they will end up with only the seccomp rules from the final test.

**Comment by weirdwiz** [comment]
Should the hook just take the syscalls allowed or blocked in the original profile or, should it append to the original profile as-is?

**Comment by vrothberg** [comment]
> My concern is with people running the command multiple times with different tests, They may expect it to be cumulative, but currently they will end up with only the seccomp rules from the final test.

I prefer to clearly document it rather than not allowing to write to pre-existing files. Especially for temporary files, I'd love to have it. We can extend the syntax in the future with, for instance, `if=...,of=...,mode=cummulative`".

> Should the hook just take the syscalls allowed or blocked in the original profile or, should it append to the original profile as-is?

That's very good question. I *think* it should append and override if a syscalls is already mentioned. @rhatdan WDYT?
