### ISSUE TITLE
oci-seccomp-bpf-hook should be able to tell from bpf that the pid 1 of container exited

### ISSUE THREAD

**Issue by rhatdan** [containers/oci-seccomp-bpf-hook#15]
The hook should not have to rely on runc sending the poststop hook and sending a signal across.

Isn't there something BPF would tell us?

**Comment by vrothberg** [comment]
I don't know if eBPF allows that but we could start another goroutine that sends a signal if the init process dies.

**Comment by vrothberg** [comment]
I don't know if eBPF allows that but we could start another goroutine that sends a signal if the init process dies.

**Comment by vrothberg** [comment]
I have an idea that might work and is not racy. We could add another trace point to scheduler for process_exit (similar to https://github.com/iovisor/bcc/blob/master/tools/exitsnoop.py#L116). As soon as the we notice that the init PID exits, we signal the go tracer. We could extend the data structure if a boolean to indicate `stop trace` or something similar.

**Comment by weirdwiz** [comment]
That is entirely possible, I should try hacking something together.
