### ISSUE TITLE
Use one hook instead of two

### ISSUE THREAD

**Issue by vrothberg** [containers/oci-seccomp-bpf-hook#19]
We can combine the two hooks into one by inspecting the inspecting the container's state in the runtime state json that is passed via stdin. @wking gives a great overview of how that can be done here: https://github.com/cri-o/cri-o/pull/1360

Thanks to @wking for the guidance!

**Comment by weirdwiz** [comment]
We won't need the poststop hook now as the hook can now exit on it's own[1] :D

[1]: #20

**Comment by vrothberg** [comment]
Fixed with #20.
