### ISSUE TITLE
Needs an RPM Spec file

### ISSUE THREAD

**Issue by rhatdan** [containers/oci-seccomp-bpf-hook#2]
@jnovy @lsm5 could you help with this.

**Comment by rhatdan** [comment]
Here is my initial stab at it.  But I am not sure how you want to build this.  I would love to get this autobuilt...

[oci-seccomp-bpf.spec.in.txt](https://github.com/containers/oci-seccomp-bpf-hook/files/3639430/oci-seccomp-bpf.spec.in.txt)

**Comment by jnovy** [comment]
Hi Dan,

seems the makefile in
https://github.com/containers/oci-seccomp-bpf-hook/blob/master/Makefile
needs additional care as the spec file refers much more files than actually
installed into the $BUILDROOT and /usr/bin/oci-seccomp-bpf is not even
there (only in /usr/libexec). Should I do a PR to fix this?

Attaching patch against your spec draft.

Jindrich

**Comment by rhatdan** [comment]
Yes, I was just throwing something together, if you could open a complete PR, that would be great.  We will need to also start this package to begin to go through the Fedora Review Process.

**Comment by jnovy** [comment]
The missing /usr/bin/oci-seccomp-bpf-hook is trivial to fix on Makefile's side.

Now these need to be added to the repo as they are completely missing:
/usr/lib/systemd/system/io.oci-seccomp-bpf.service
/usr/lib/systemd/system/io.oci-seccomp-bpf.socket

Once done I can file Fedora review. Maybe @vrothberg can help with these?

**Comment by rhatdan** [comment]
@jnovy could you open a PR with the spec file you want to run with?

**Comment by vrothberg** [comment]
I am going to close given it's packaged.
