### ISSUE TITLE
Need to hook up cirrus testing.

### ISSUE THREAD

**Issue by rhatdan** [containers/oci-seccomp-bpf-hook#3]
- [x] Create new GCE Project
- [x] Grant stake-holders 'owner' IAM role (including James) in new project
- [x] Ask James Russell to move billing account
- [x] Create 'imgts-<number>' IAM service account in new project
      - Use description: "Account for <new repo> access to update VM Image metadata"
      - Create and store key (JSON) file locally for use later
- [x] Grant 'imgts-<number>' IAM roles in new project
      - Service Account User
- [x] Grant 'imgts-<number>' IAM roles in libpod project
      - Compute Image Label Writer
      - Service Account User
- [x] Create 'cirrus-ci' IAM service account in new project
      - Use description: "Account for <new repo> access to manage resources for Cirrus-CI"
      - Create and store key (JSON) file locally for use later
- [x] Grant 'cirrus-ci' IAM roles in new project
      - Storage Object Admin
      - Storage Admin
      - Compute Instance Admin (v1)
      - Compute OS Admin Login
      - Compute OS Login
      - Service Account User
- [x] Grant 'cirrus-ci' IAM roles in libpod project
      - Compute Image User
      - Service Account User
- [x] In Github Org. settings, enable Cirrus-CI App. access to new repo.
- [x] Go to `https://cirrus-ci.com/github/containers/<new repo name>` settings
      - Disable "Require approval for builds from users without write permissions"
      - Enable "Decrypt Secured Environment Variables for builds initialized by:"
      - Use the encryption box to generate `ENCRYPTED[abc123]` database keys for both service accounts (`imgts-<number>` and `cirrus-ci`) JSON file contents.  Note the strings temporarily.
      - Use the encryption box to generate database keys for the libpod project ID and the complete (fake) e-mail name of the `imgts-<number>` service account.
- [x] Add the new google project ID to [the *Google Cloud Platform projects* list under the *Monitored accounts* section of the Stackdriver workspace settings page](https://app.google.stackdriver.com/settings/accounts/cloud_accounts?project=libpod-218412).
- [x] Clone and create working branch for new repo.
- [x] Open PR for working branch
- [x] Port `.cirrus.ci` over, based on another project, like `buildah`.
- [x] Port over `hack/get_ci_vm.sh`, edit as needed until it works.
- [x] Implement simple tasks/scripts, pushing to PR, and updating until Cirrus-CI working properly.
- [x] Finalize PR based on project needs.

**Comment by cevich** [comment]
Thx, got it.

**Comment by cevich** [comment]
update: My plate is mostly clear now to work on this next week.

**Comment by rhatdan** [comment]
@cevich any progress?

**Comment by cevich** [comment]
thanks for the poke, no unfortunately not, I should do something about that...like, get started.
