### ISSUE TITLE
Build failure in Fedora 32/rawhide due to update to gcc 10

### ISSUE THREAD

**Issue by jnovy** [containers/oci-seccomp-bpf-hook#31]
Please see:
https://koji.fedoraproject.org/koji/taskinfo?taskID=41215628

It might be connected with update to gcc-10. There is a risk this package would be dropped if the build failure isn't fixed. Any hints?

Thanks,
Jindrich

**Comment by vrothberg** [comment]
@weirdwiz, do you have time to look at that?

**Comment by vrothberg** [comment]
@jnovy, are you still seeing the error in Rawhide?
