### ISSUE TITLE
Build failure on RHEL 8.2

### ISSUE THREAD

**Issue by slashTPA** [containers/oci-seccomp-bpf-hook#37]
Hi,
trying to make binary fails on my RHEL8.2:

$ make binary
GO111MODULE=on go build -mod=vendor -o bin/oci-seccomp-bpf-hook -ldflags "-X main.version=1.0.0" github.com/containers/oci-seccomp-bpf-hook
# github.com/iovisor/gobpf/bcc
vendor/github.com/iovisor/gobpf/bcc/module.go:32:10: fatal error: bcc/bcc_common.h: No such file or directory
 #include <bcc/bcc_common.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:49: binary] Fehler 2

Did anyone succeed to install it on RHEL8.2? 
If so, could you kindly post the steps? 
I'm concerned a bit due to "No match for argument: bcc-devel" on RHEL. How to mitigate?

Cheers.

**Comment by vrothberg** [comment]
bcc-devel is not available on RHEL 8.2. `oci-seccomp-bpf-hook` will be available on RHEL 8.3 where I assume bcc-devel will be available as well.
