### ISSUE TITLE
Better names for the env variables?

### ISSUE THREAD

**Issue by fgiloux** [containers/oci-seccomp-bpf-hook#43]
Hi

I was trying to compile on Fedora 32 silverblue and had this funny thing: the compilation was failing and complaining on the link command having wrong arguments. Looking at the Makefile there are a few env variables that get defined if not already set, especially:
VERSION ?= $(shell cat ./VERSION)
The thing is that this variable is defined per default with "32 (Container Image)" on my system, replacing the value with the content of the VERSION file solved the issue.
Would it make sense to use variables with a prefix, something like OCISBH_VERSION for avoiding this?

Regards,

Frédéric

**Comment by rhatdan** [comment]
Sure, could you open a PR to make the change?

**Comment by fgiloux** [comment]
Sure. That's done.

**Comment by vrothberg** [comment]
Thanks for reaching out and for the PR!

I am quite surprised that Silverblue is setting VERSION. It seems common practice to use that the way we used to do it.

With #43 being merged, I am closing the issue.
