### ISSUE TITLE
build fails on CentOS

### ISSUE THREAD

**Issue by lsm5** [containers/oci-seccomp-bpf-hook#45]
Trying to build 1.1.0 rpm on OBS for CentOS, and it fails with:

```
[  168s] _build/src/github.com/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc/module.go:98:40: too many arguments in call to _Cfunc_bpf_module_create_c_from_string
[  168s] 	have (*_Ctype_char, number, **_Ctype_char, _Ctype_int, _Ctype__Bool, nil)
[  168s] 	want (*_Ctype_char, _Ctype_uint, **_Ctype_char, _Ctype_int, _Ctype__Bool)
```

**Comment by lsm5** [comment]
https://build.opensuse.org/public/build/devel:kubic:libcontainers:stable/CentOS_7/x86_64/oci-seccomp-bpf-hook/_log

**Comment by weirdwiz** [comment]
```
[  128s] [218/271] installing bcc-0.10.0-1.el7
```
the function definition was changed, bcc >= 0.11.0 , you'll need to update bcc

**Comment by lsm5** [comment]
> ```
> [  128s] [218/271] installing bcc-0.10.0-1.el7
> ```
> 
> the function definition was changed in bcc >= 0.11.0 , you'll need to update bcc

Thanks. I guess I'll just wait until CentOS updates bcc then, unless there's enough demand for me to package it separately on OBS. Closing...
