### ISSUE TITLE
OCI runtime error when executing hook

### ISSUE THREAD

**Issue by doctormay6** [containers/oci-seccomp-bpf-hook#48]
I tried using this tool with a container that I made and it fails to run the hook. The container was originally made for Docker and runs Apache Guacamole as well as Firefox. If you need more information on the container, see [my repo](https://github.com/doctormay6/foxception) or ask me.

Steps to reproduce the error: (Fedora 32 server)
`$ sudo dnf install oci-seccomp-bpf-hook podman git`
`$ git clone https://github.com/doctormay6/foxception.git`
`$ cd foxception`
`$ sudo podman build --tag foxception:seccomp -f ./Dockerfile`
`$ sudo podman run -d --shm-size=1G --annotation io.containers.trace-syscall=of:foxception.json foxception:seccomp`
Error message at this point: 
`Error: error executing hook '/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook' (exit code: 1): OCI runtime error`

I'll run podman in debug log level and see if I can pinpoint exactly where it fails or if there is a more informative error message.

**Comment by doctormay6** [comment]
With journalctl I can see a fatal message:
`paths mus be absolute: \"\": invalid annotation: please refer to the syslog (e.g., journalctl(1)) for more details`

**Comment by weirdwiz** [comment]
the annotation requires the absolute path for the output profile, so your annotation would look something like this 
```
io.containers.trace-syscall=of:/path/to/the/profile.json
```

**Comment by vrothberg** [comment]
Thanks for reaching out! As @weirdwiz said, we enforce absolute paths. Relative paths can be error prone with so many different tools in play.

**Comment by doctormay6** [comment]
Ah, I can't believe I didn't try that... "But I tried everything!" Thanks for clearing that up for me, it is working now.

**Comment by doctormay6** [comment]
Where in the repo can I begin looking for the right place to add that functionality?

**Comment by rhatdan** [comment]
Great, @doctormay6 Looking forward to it. The error message should be a improved to tell the user that they need to specify a full path.
