### ISSUE TITLE
Add/infer architectures for generated seccomp profiles

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-seccomp-bpf-hook#54]
Hey :wave:, I think we should definitely add some architectures to the generated seccomp profiles. One approach could be that we just add all architectures, or we try to infer them from `runtime.GOARCH`. WDYT?

**Comment by vrothberg** [comment]
> One approach could be that we just add all architectures,

Would there a benefit over adding none at all?

>  or we try to infer them from runtime.GOARCH

Sounds good :+1:
