### ISSUE TITLE
Request: Cut v1.2.0

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-seccomp-bpf-hook#58]
Hey :wave:, may I ask you to cut a new release that we can get the architecture feature in? I'm on my way packaging it for openSUSE distributions and it would be cool to have the feature landed. :innocent:

**Comment by vrothberg** [comment]
Sure. Would be 1.2.0 though :)

**Comment by saschagrunert** [comment]
> Sure. Would be 1.2.0 though :)

Makes sense :grin:
