### ISSUE TITLE
not enough arguments in call to _C2func_bpf_attach_uprobe

### ISSUE THREAD

**Issue by jouros** [containers/oci-seccomp-bpf-hook#69]
$ go get -u github.com/containers/oci-seccomp-bpf-hook
# github.com/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc
github.com/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc/module.go:261:33: not enough arguments in call to _C2func_bpf_attach_uprobe
	have (_Ctype_int, uint32, *_Ctype_char, *_Ctype_char, _Ctype_ulong, _Ctype_int)
	want (_Ctype_int, uint32, *_Ctype_char, *_Ctype_char, _Ctype_ulong, _Ctype_int, _Ctype_uint)

Same error with:
oci-seccomp-bpf-hook$ make binary
GO111MODULE=on go build -mod=vendor -mod=vendor -o bin/oci-seccomp-bpf-hook -ldflags "-X main.version=v1.2.1-dev" github.com/containers/oci-seccomp-bpf-hook
# github.com/iovisor/gobpf/bcc
vendor/github.com/iovisor/gobpf/bcc/module.go:261:33: not enough arguments in call to _C2func_bpf_attach_uprobe
	have (_Ctype_int, uint32, *_Ctype_char, *_Ctype_char, _Ctype_ulong, _Ctype_int)
	want (_Ctype_int, uint32, *_Ctype_char, *_Ctype_char, _Ctype_ulong, _Ctype_int, _Ctype_uint)
make: *** [Makefile:49: binary] Error 2

I compiled bcc from source. My system is Ubuntu 20.04

**Comment by ahmadalli** [comment]
I'm facing the same issue

**Comment by vrothberg** [comment]
Thanks for reaching out and apologies for the long silence!

I suspect that the `bcc-devel` library on Ubuntu is too old.  I am running Fedora 33 and do not encounter an issue.

**Comment by ahmadalli** [comment]
If I remember correctly, I've tried compiling the bcc and was still facing this error

**Comment by jouros** [comment]
I did that too, I compiled bcc.

Br, Jouni
