### ISSUE TITLE
Allow recording multiple processes into the same file

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-seccomp-bpf-hook#74]
We can have multiple containers within a single pod in Kubernetes, but we cannot have annotations on a container level. This means if we run the hook in k8s with multiple containers, we will overwrite the output file depending on who is the last writer:

https://github.com/containers/oci-seccomp-bpf-hook/blob/50e7112d7d2677e8f44ef1d6e743397c1de22521/oci-seccomp-bpf-hook.go#L371-L373

My idea is now to specify an option to write and append a list of profiles to a file instead of overwriting it. WDYT?

It wouldn't be easy to preserve the JSON format of the file. We would have to track how much other processes are running and will probably run into races. We could just add the profiles line by line but this would not be valid JSON any more.

**Comment by vrothberg** [comment]
Thanks for reaching out!

At the moment, we really have one file per container.  Appending multiple ones would break backwards compat.  Synchronizing the writes can be challenging as well.

Conceptually, we could:
* Acquire a lock - either a global one or per-profile.
* Append the profile to file and maybe write a header or something similar to identify which profiles belongs to which container.
* Release the lock.

But that'll break backwards compat and sacrifice usability for the single-container use case in Podman, for instance.

Do you know why Kubernetes doesn't allow per-container annotations?  There are so many (useful) use cases and it's quite common at least in Podman to do that.  How are the chances to extend Kubernetes?

**Comment by saschagrunert** [comment]
Extending Kubernetes is not a short-term option unfortunately. We could add logic to CRI-O to modify the annotation output path and suffix the container name.

One common pattern when speaking about annotations in Kubernetes is that we suffix the key with the container name.

For example:
```
io.containers.trace-syscall/my-container = of:/path/to/profile.json
```

But now modifying the output path within the hook does not make sense to me. :thinking:

**Comment by vrothberg** [comment]
Great idea!

So CRI-O would understand the annotation and add custom logic to pass a per-container profile down to the runtime?

**Comment by saschagrunert** [comment]
> Great idea!
> 
> So CRI-O would understand the annotation and add custom logic to pass a per-container profile down to the runtime?

Yeah I think this would be doable. I'll draft a PR for that. Thank you for your thoughts! :pray:

**Comment by vrothberg** [comment]
Closing in favor of cri-o/cri-o#4544. Thanks, @saschagrunert !
