### ISSUE TITLE
oci-seccomp-bpf-hook exits with OCI runtime error Code 127

### ISSUE THREAD

**Issue by Kvlbs** [containers/oci-seccomp-bpf-hook#75]
Hello , Sorry if this is the wrong place to raise this issue or its something too basic.  

I am following the [same blog](https://www.redhat.com/sysadmin/container-security-seccomp) and same procedure as above.
Fresh install of Fedora 33 from Fedora-Workstation-Live-x86-64-33-1.2.iso
Then  dnf install oci-seccomp-bpf-hook 

The images were created
[root@fedora labs]# sudo podman run fedora:33 cat /etc/fedora-release
Fedora release 33 (Thirty Three)

However,
root@fedora labs]# sudo podman run --annotation io.containers.trace-syscall=of:/tmp/ls.json fedora:33 ls / > /dev/null  

Error: error executing hook `/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook` (exit code: 127): OCI runtime error

journalctl is empty
root@fedora labs]# journalctl --since "10 minutes ago" | grep seccomp

Any pointers on something I might have missed?

_Originally posted by @Kvlbs in https://github.com/containers/oci-seccomp-bpf-hook/issues/64#issuecomment-805046279_

**Comment by vrothberg** [comment]
Thanks for reaching out.  Can you share the output of `podman info`?  There was a regression in `crun` which has been fixed earlier this year.

**Comment by Kvlbs** [comment]
Hello, Here is the output from podman info 
[labs@fedora bcc]$ sudo podman info

host:

  arch: amd64

  buildahVersion: 1.16.1

  cgroupManager: systemd

  cgroupVersion: v2

  conmon:

    package: conmon-2.0.21-3.fc33.x86_64

    path: /usr/bin/conmon

    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'

  cpus: 1

  distribution:

    distribution: fedora

    version: "33"

  eventLogger: journald

  hostname: fedora

  idMappings:

    gidmap: null

    uidmap: null

  kernel: 5.8.15-301.fc33.x86_64

  linkmode: dynamic

  memFree: 1765695488

  memTotal: 4119363584

  ociRuntime:

    name: crun

    package: crun-0.15-5.fc33.x86_64

    path: /usr/bin/crun

    version: |-

      crun version 0.15

      commit: 56ca95e61639510c7dbd39ff512f80f626404969

      spec: 1.0.0

      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL

  os: linux

  remoteSocket:

    path: /run/podman/podman.sock

  rootless: false

  slirp4netns:

    executable: ""

    package: ""

    version: ""

  swapFree: 2059399168

  swapTotal: 2059399168

  uptime: 3m 30.96s

registries:

  search:

  - registry.fedoraproject.org

  - registry.access.redhat.com

  - registry.centos.org

  - docker.io

store:

  configFile: /etc/containers/storage.conf

  containerStore:

    number: 21

    paused: 0

    running: 0

    stopped: 21

  graphDriverName: overlay

  graphOptions:

    overlay.mountopt: nodev,metacopy=on

  graphRoot: /var/lib/containers/storage

  graphStatus:

    Backing Filesystem: btrfs

    Native Overlay Diff: "false"

    Supports d_type: "true"

    Using metacopy: "true"

  imageStore:

    number: 3

  runRoot: /var/run/containers/storage

  volumePath: /var/lib/containers/storage/volumes

version:

  APIVersion: 2.0.0

  Built: 1601853924

  BuiltTime: Mon Oct  5 01:25:24 2020

  GitCommit: ""

  GoVersion: go1.15.2

  OsArch: linux/amd64

  Version: 2.1.1

**Comment by vrothberg** [comment]
Thank you!  Indeed, `crun`, `podman` and friends are quite old.  Could you run a `dnf update` and try again?

**Comment by Kvlbs** [comment]
It works thanks :)
