### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by rhatdan** [containers/oci-seccomp-bpf-hook#86]

**Comment by cevich** [comment]
***Supporting/Required changes:***

- [ ] Update status link in `README.md`

(I'll update this comment as/if I find more)

**Comment by cevich** [comment]
@rhatdan By my eyes, this repo. looks like it might be a really low-friction candidate for renaming.  All I could find locally was the *readme*. Though I'll keep on the lookout if other repos. contain any links to this one.

**Comment by rhatdan** [comment]
Renamed.
