### ISSUE TITLE
Consider using libbpf

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-seccomp-bpf-hook#93]
If we utilize [libbpf](https://github.com/libbpf/libbpf), then we can produce a smaller binary which also runs faster and minimizes the runtime dependencies. The overall architecture of the hook could be simplified as well. I created a syscall recorder project for demonstration purposes: https://github.com/saschagrunert/syscall-recorder

Building the main application (the syscall-recorder) requires bpftool, clang, llvm, libbpf, libelf, libz and libseccomp (for converting the syscall IDs to names). Statically linking is now also possible.

For my demo and to keep things simple, I decided to not fork within the recorder and build a small wrapper around systemd-run: https://github.com/saschagrunert/syscall-recorder/blob/main/hack/oci-hook/hook.go. Right now the recorder is not able to produce a full seccomp profile, but writes a list of syscalls to the target location.

![demo](https://user-images.githubusercontent.com/695473/137457136-f3c610d5-e920-4eac-8d70-6dbf2c821de3.gif)

What are your thoughts on that?

**Comment by vrothberg** [comment]
I don't understand the proposal and problem statement. Can you elaborate? Is it to rewrite oci-seccomp-bpf-hook in C with libbpf?

**Comment by weirdwiz** [comment]
> What versions of RHEL support this?
RHEL 8.2+

**Comment by rafaeldtinoco** [comment]
Take a look at https://github.com/aquasecurity/btfhub/ to make this work with CO-RE and old kernels (specifically at recent work being done at: https://github.com/aquasecurity/btfhub/tree/main/tools, which will be upstreamed shortly).

**Comment by vrothberg** [comment]
Any updates, @weirdwiz?  I want to make sure that @saschagrunert's request is not falling from our radar.

**Comment by vrothberg** [comment]
OK, let's unblock the issue.  @weirdwiz is busy with his internship at Red Hat's storage team.  If others want to give it a shot, feel free to self-assign or drop a comment.

**Comment by saschagrunert** [comment]
In the meanwhile we released a first integration within the security-profiles-operator: https://github.com/kubernetes-sigs/security-profiles-operator/tree/main/internal/pkg/daemon/bpfrecorder

Packaging a generic libbpf-based application seems to be the most tricky part here. On the other side, we probably do not have to support a custom BTF if we focus on Fedora/RHEL packaging in the first place.

@vrothberg I can put it in our Node Observability backlog if you don't mind, because we plan to work on ebpf applications in any case in mid-term.

**Comment by vrothberg** [comment]
@saschagrunert did you find time looking into it?

**Comment by saschagrunert** [comment]
@vrothberg unfortunately not directly, because I think we should clarify how to package the application before moving forward. I'm working with other teams on solving that issue right now, but I think it will take some time (months).

libbpf still seems not to be supported with all features for all kernels by the way. For example ring buffer maps are not supported by Linux < 5.8. Not sure if that is a problem we can encounter.

**Comment by saschagrunert** [comment]
Let's close it for now, it does not have the priority that I can work on it in the near future.
